---
title: "eds221_day2-comp"
author: "Daniel Kerstan"
date: "8/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(palmerpenguins)
library(tidyverse)
```

## Make some vectors and check them out

```{r}
dogs <- c("teddy", 40, TRUE, 5)

dogs

#check the class:

class(dogs)




```

```{r}
dog_age <- c(1.4, 5.2, 6, 10)
class(dog_age)
typeof(dog_age)

dog_miles <- c(4L, 5L, 6L)
class(dog_miles)
typeof(dog_miles)

is.character(dog_miles)
is.character(dogs)


```


```{r}
dog_food <- c(teddy = "purina",
              khora = "alpo",
              waffle = "fancy feast",
              banjo = "blue diamond")

dog_food
class(dog_food)

khora_food <- dog_food[2]
dog_food["khora"]

khora_food

dog_size <- c(teddy = 50, khora = 55)

test <- 6 + dog_size[2]

test

```

```{r}
cars <- c("red", "white", "yellow", "silver", "black")

cars[2:5]

i <- 3

cars[i]

i <- c(1, 5, 7)

cars[i]

cars[3] <- "BURRITOS"

```


## Lissts in R

```{r}
urchins <- list("blue",
                c(1, 2, 3),
                FALSE,
                seq(from = 0, to = 50, by = 0.5))

urchins

urchins[[1]]
#returns the content of the element
urchins[1]
#returns list of 1 element
```


```{r}
tacos <- list(topping = c("onion", "cilantro", "guacamole"),
              filling = c("breans", "meat", "veggies"),
              price = c(6.75, 8.25, 9.50))

tacos

tacos_price <- tacos[[3]]

tacos_price


tacos$filling
```


## Data frames

```{r}
fruit <- data.frame(type = c("apple", "banana", "peach"),
                    mass = c(130, 195, 150))

fruit
class(fruit)
class(fruit$mass)

fruit[[2, 2]]

fruit$type

fruit[, 1]
```
















